"""Creator intelligence: what each studied creator builds, sells and teaches, and what that
makes possible for us.

Reads only local evidence:
  packages/library/corpus/youtube/<channel>/videos.json   titles, views (channel listing)
  packages/library/corpus/youtube/facts.jsonl              mined techniques/models/packs
  packages/library/corpus/youtube/links.jsonl              classified description links
  packages/library/corpus/youtube/<channel>/steps/*.md     step lists (when generated)
  brands/_business/creators.yaml                           public prices, checked by hand
  workflows/manifest.json                                  what we can already run

    uv run --with pyyaml packages/strategy/creator_intel.py   -> docs/creators/CREATOR-INTEL.md
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[2]
CORPUS = REPO / "packages" / "library" / "corpus" / "youtube"
CREATORS = REPO / "brands" / "_business" / "creators.yaml"
MANIFEST = REPO / "workflows" / "manifest.json"
OUT = REPO / "docs" / "creators" / "CREATOR-INTEL.md"
STUDIED = ("loratech", "matrixlabai", "kiubai", "artificialquotient")

# Technique -> keywords that indicate we already hold a workflow for it (manifest paths/types).
CAPABILITIES: dict[str, tuple[str, ...]] = {
    "Character dataset generation": ("dataset",),
    "Character LoRA training": ("lora",),
    "RefMod (no-training character)": ("refmod",),
    "Motion transfer (SCAIL)": ("scail",),
    "Image to video (WAN/LTX)": ("i2v", "ltx", "wan"),
    "Long / infinite video (H3)": ("extend", "long-video", "keyframes", "infinite"),
    "Carousel from one photo": ("carousel",),
    "Face swap (consented)": ("faceswap",),
    "Image edit / img2img": ("qwen", "klein"),
    "Upscale": ("upscale", "de-rope", "2mp"),
}
TOOL_RE = re.compile(r"^(.{2,40}?)\s+(?:AI\s+)?(?:Tutorial|Review|Guide)\b", re.I)


def _jsonl(p: Path) -> list[dict[str, Any]]:
    if not p.exists():
        return []
    return [json.loads(line) for line in p.read_text(encoding="utf-8").splitlines() if line.strip()]


def _videos(ch: str) -> dict[str, Any]:
    p = CORPUS / ch / "videos.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {"videos": []}


def _fmt_views(v: int | None) -> str:
    if v is None:
        return "?"
    return f"{v/1000:.1f}k" if v >= 1000 else str(v)


def capability_matrix() -> list[tuple[str, list[str]]]:
    man = json.loads(MANIFEST.read_text(encoding="utf-8")) if MANIFEST.exists() else {"workflows": []}
    rows = []
    for cap, keys in CAPABILITIES.items():
        hits = sorted({w["canonical"].removeprefix("workflows/") for w in man["workflows"]
                       if any(k in w["canonical"].lower() for k in keys)})
        rows.append((cap, hits))
    return rows


def build() -> str:
    creators = yaml.safe_load(CREATORS.read_text(encoding="utf-8"))["creators"]
    facts = _jsonl(CORPUS / "facts.jsonl")
    links = _jsonl(CORPUS / "links.jsonl")
    by_channel_facts = defaultdict(list)
    for f in facts:
        by_channel_facts[f.get("channel")].append(f)

    out = ["# Creator intelligence", "",
           "Generated by `packages/strategy/creator_intel.py` from local evidence (channel listings, "
           "mined transcripts, description links, hand-checked public prices). Do not edit by hand.", "",
           "## At a glance", "",
           "| Creator | Followers | Videos | Transcripts mined | What they build | How they make money | Public price |",
           "|---|---|---|---|---|---|---|"]
    for ch in STUDIED:
        c, v = creators.get(ch, {}), _videos(ch)
        products = c.get("products", [])
        money = ", ".join(sorted({p["platform"] for p in products})) or "unknown"
        price = "; ".join(f"{p['name']}: {p['price']}" for p in products
                          if p.get("price") not in (None, "free")) or "unknown"
        out.append(f"| **{c.get('display', ch)}** | {_fmt_views(v.get('followers'))} | {len(v['videos'])} | "
                   f"{len(by_channel_facts[ch])} | {c.get('builds', '')} | {money} | {price} |")
    out.append("")

    for ch in STUDIED:
        c, v = creators.get(ch, {}), _videos(ch)
        out += [f"## {c.get('display', ch)}", "", f"**Audience:** {c.get('audience', 'unknown')}", ""]
        out += ["### What they sell", "", "| Product | Platform | Price | Contents | Checked |", "|---|---|---|---|---|"]
        for p in c.get("products", []):
            name = f"[{p['name']}]({p['url']})" if p.get("url") else p["name"]
            extra = f" ({p['members']} members)" if p.get("members") else ""
            out.append(f"| {name} | {p['platform']} | {p['price']}{extra} | {p['contents']} | {p['read']} |")
        out.append("")

        tech = Counter()
        for f in by_channel_facts[ch]:
            for kind in ("model", "node_pack", "technique", "creative"):
                for it in f["facts"].get(kind, []):
                    tech[f"{kind}: {it['value']}"] += 1
        if tech:
            out += ["### What they teach most (mentions across mined videos)", "",
                    ", ".join(f"{k} ({n})" for k, n in tech.most_common(18)), ""]

        ch_links = [l for l in links if l["channel"] == ch]
        free_wf = sorted({l["url"] for l in ch_links if l["fetchable"]})
        paid = sorted({l["url"].split("?")[0] for l in ch_links if l["paid"]})
        repos = sorted({l["url"] for l in ch_links if l["kind"] in ("github_repo", "huggingface")})
        out += ["### Workflows and resources", "",
                f"- Free workflow files linked: {len(free_wf)}" + ("" if not free_wf else " — " + ", ".join(free_wf)),
                f"- Paid access: {', '.join(paid) if paid else 'none linked in descriptions'}",
                f"- Repos and model pages linked: {len(repos)}", ""]

        vids = sorted(v["videos"], key=lambda x: -(x.get("views") or 0))
        mined = {f["video_id"] for f in by_channel_facts[ch]}
        out += ["### Top videos", "", "| Views | Title | Mined | Steps |", "|---|---|---|---|"]
        for x in vids[:15]:
            steps = CORPUS / ch / "steps" / f"{x['id']}.md"
            out.append(f"| {_fmt_views(x.get('views'))} | [{x['title']}](https://www.youtube.com/watch?v={x['id']}) | "
                       f"{'yes' if x['id'] in mined else 'no'} | "
                       f"{'[steps](../../' + steps.relative_to(REPO).as_posix() + ')' if steps.exists() else '—'} |")
        out.append("")

    aq = _videos("artificialquotient")["videos"]
    tools = Counter()
    for x in aq:
        m = TOOL_RE.match(x.get("title") or "")
        if m:
            tools[m.group(1).strip()] += x.get("views") or 0
    if tools:
        out += ["## The paid AI-tool market (from Artificial Quotient's titles)", "",
                "Each is a product people pay for. Where we already run an open-source equivalent, "
                "the same outcome can be sold as a service at our cost.", "",
                "| Tool | Views on its video(s) |", "|---|---|"]
        out += [f"| {t} | {_fmt_views(n)} |" for t, n in tools.most_common(40)]
        out.append("")

    out += ["## Capability matrix: what we can already run", "",
            "| Technique taught | Our workflows (workflows/) |", "|---|---|"]
    for cap, hits in capability_matrix():
        out.append(f"| {cap} | {', '.join(f'`{h}`' for h in hits[:5]) + (' …' if len(hits) > 5 else '') if hits else '**gap**'} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
