"""A proposal for each of the 50 ideas, built from the numbers and pipelines the studio already holds.

Each proposal joins:
- brands/_business/ideas.yaml and business_os.cost (buyer, offer, price, costs, scenarios),
- the idea's studio template (steps, what runs each one, gaps, consent and 18+ gates),
- the canvas catalogue (which ComfyUI workflow or studio code runs a step),
- infra/runpod/download-plan.json (whether that workflow's models can be fetched).

Nothing is typed twice, so a proposal cannot disagree with IDEAS-50.md or the canvas.
Writes docs/proposals/<id>-<slug>.md and docs/proposals/README.md.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import business_os as bos  # noqa: E402

CATALOG = REPO / "packages" / "studio-ui" / "catalog" / "nodes.json"
TEMPLATES = REPO / "brands" / "_templates" / "workflows"
PLAN = REPO / "infra" / "runpod" / "download-plan.json"
OUT = REPO / "docs" / "proposals"
BUCKETS = ("resolved", "auto_download", "creator_private", "manual", "unresolved")
RUNS = {"comfy": "ComfyUI on the pod", "python": "studio code", "publish": "publisher (draft first)",
        "router": "hosted model", "input": "you provide", "brand": "brand.yaml", "human": "a person decides"}


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def template(idea_id: str) -> tuple[Path, dict[str, Any]]:
    p = next(TEMPLATES.glob(f"{idea_id.lower()}-*.studio.json"))
    return p, json.loads(p.read_text(encoding="utf-8"))


def model_status() -> dict[str, dict[str, list[str]]]:
    plan = json.loads(PLAN.read_text(encoding="utf-8")) if PLAN.exists() else {}
    out: dict[str, dict[str, list[str]]] = {}
    for b in BUCKETS:
        for r in plan.get(b, []):
            for u in r.get("used_by", []):
                out.setdefault(u, {}).setdefault(b, []).append(r["file"])
    return out


def build(idea: dict[str, Any], costed: bos.Costed, cat: dict[str, dict[str, Any]],
          models: dict[str, dict[str, list[str]]]) -> dict[str, Any]:
    path, wf = template(idea["id"])
    steps = []
    for n in wf["nodes"]:
        spec = cat.get(n["kind"])
        gap = next((g for g in wf["gaps"] if g["node"] == n["id"]), None)
        be = (spec or {}).get("backend", {})
        canonical = f"workflows/{be['workflow']}" if be.get("kind") == "comfy" else None
        steps.append({"kind": n["kind"], "label": (spec or {}).get("label", gap["step"] if gap else n["kind"]),
                      "runs": "not runnable yet" if gap or not spec else RUNS[be["kind"]],
                      "detail": gap["reason"] if gap else (canonical or be.get("module") or be.get("profile") or ""),
                      "missing": be.get("missing", "") if gap else "",
                      "needs_setup": (spec or {}).get("needs_setup"),
                      "workflow": canonical, "gap": bool(gap), "consent": bool((spec or {}).get("consent")),
                      "adult": bool((spec or {}).get("adult")), "models": models.get(canonical, {}) if canonical else {}})
    work = [s for s in steps if s["kind"] not in {"brief", "reference-images", "product-photo", "video-clip", "song", "brand-kit"}]
    ready = [s for s in work if not s["gap"]]
    return {"idea": idea, "costed": costed, "template": path, "wf": wf, "steps": steps,
            "ready_share": (len(ready) / len(work)) if work else 0.0,
            "gaps": [s for s in steps if s["gap"]],
            "setup": [s for s in steps if s["needs_setup"] and not s["gap"]],
            "decisions": list(idea.get("decisions") or []),
            "blocked_models": sorted({f for s in steps for b in ("creator_private", "manual", "unresolved")
                                      for f in s["models"].get(b, [])})}


def _m(x: float | None) -> str:
    return bos._money(x)


def render(p: dict[str, Any], families: dict[str, str]) -> str:
    i, c = p["idea"], p["costed"]
    rate = bos.GPU_RATES[i.get("gpu", "a100-80gb")]
    labour = bos.labor_hours(i)
    diagram = f"../diagrams/ideas/{i['id'].lower()}.workflow.html"
    L = [f"# {i['id']} {i['name']}", "",
         f"Proposal generated by `packages/strategy/proposals.py` from `brands/_business/ideas.yaml`, the studio "
         f"template and the pod model plan. Do not edit by hand.", "",
         "> Planning estimates, not forecasts. Client counts are scenarios; image throughput is measured "
         "(444 images per GPU-hour), video throughput and the GPU rate are assumptions until a live run replaces them.", "",
         f"**Family:** {families[i['family']]}  ", f"**Buyer:** {i['buyer']}  ", f"**Offer:** {i['offer']}  ",
         f"**Price:** {_m(i['price_usd'])} per client per month" + (" (per unit, see buyer)" if "units =" in i["buyer"] else ""), "",
         "## Why it sells", "", f"{i['evidence']}.", "",
         "## How we deliver it", "",
         f"Studio template: [`{p['template'].name}`](../../{p['template'].relative_to(REPO).as_posix()}). "
         f"Diagram: [{i['id'].lower()}.workflow.html]({diagram}).", "",
         "| Step | Runs on | Detail | Gate |", "|---|---|---|---|"]
    for s in p["steps"]:
        gate = " ".join(g for g, on in (("18+", s["adult"]), ("Consent", s["consent"])) if on) or "—"
        detail = f"`{s['detail']}`" if s["detail"] and not s["gap"] else s["detail"]
        if s["needs_setup"] and not s["gap"]:
            detail += f" (needs setup: BLOCKERS {s['needs_setup']['blocker']})"
        L.append(f"| {s['label']} | {s['runs']} | {detail} | {gate} |")
    L += ["", f"{round(p['ready_share'] * 100)}% of the working steps run today.", "",
          "## Numbers", "",
          f"Cost to serve one client a month: **{_m(c.cost_per_client)}** = {i['gpu_hours']} GPU-hours × "
          f"${rate.usd_per_hour}/h + {_m(i['api_usd'])} APIs + {labour:g} h labour × ${bos.LABOR_USD_PER_HOUR:g}/h "
          f"+ {bos.FEE_RATE:.0%} payment fees.", "",
          "| Scenario | Clients | Monthly revenue | Monthly cost | Profit | Margin | Setup payback |",
          "|---|---|---|---|---|---|---|"]
    for k in ("low", "base", "high"):
        s = c.scenarios[k]
        pay = "—" if s["payback_months"] is None else f"{s['payback_months']} mo"
        L.append(f"| {k} | {s['clients']} | {_m(s['mrr'])} | {_m(s['monthly_cost'])} | {_m(s['profit'])} | {s['margin']:.0%} | {pay} |")
    L += ["", f"Setup budget {_m(i['setup_usd'])}. Fixed monthly spend {_m(i['fixed_usd'])}. First cash in about "
          f"{i['first_cash_days']} days.", "",
          "## What is not ready", ""]
    if p["gaps"]:
        L += [f"- **{g['label']}**: {g['detail']}" + (f" Missing: {g['missing']}" if g["missing"] else "") for g in p["gaps"]]
    for s in p["setup"]:
        L.append(f"- **{s['label']}** needs setup (`docs/BLOCKERS.md` item {s['needs_setup']['blocker']}): {s['needs_setup']['what']}")
    if p["blocked_models"]:
        L.append(f"- Models with no public source yet (see `infra/runpod/download-plan.json`): {', '.join(p['blocked_models'])}")
    if not p["gaps"] and not p["setup"] and not p["blocked_models"]:
        L.append("- Nothing structural. Every step has a backend and every model it names has a source; it still needs a live run.")
    L += ["- No step has been run end to end on a GPU for this offer yet. Queued is not success.", ""]
    if p["decisions"]:
        L += ["## Decisions on the gaps", ""] + [f"- {d}" for d in p["decisions"]] + [""]
    L += [
          "## First 30 days", "",
          f"1. **Week 1: prove it.** Run the template on the pod with owned or fictional inputs; record real GPU minutes "
          f"and replace the {i['gpu_hours']} GPU-hour estimate.",
          "2. **Week 2: pilot.** One client at a reduced price in exchange for a case study and permission to show results.",
          f"3. **Weeks 3-4: sell.** Pitch {i['buyer'].split('(')[0].strip().lower()} with the pilot; target the low scenario "
          f"({c.scenarios['low']['clients']} clients) before scaling.",
          ("4. **Close the gaps** listed above, or sell the version without those steps and say so." if p["gaps"]
           else "4. **Automate** the recurring delivery with the studio canvas and the dry-run plan check."), "",
          "## Risks and rules", "", f"- Risk: {i['risk']}.", f"- Compliance: {i['compliance']}."]
    if p["wf"].get("consent_required"):
        L.append("- Uses faces or characters: owned, consented or fictional likenesses only, with the release on file.")
    if any(s["adult"] for s in p["steps"]) or i["family"] == "adult":
        L.append("- 18+ line: fictional adults only, separate entity and payments, never on Ongea Pesa or EPALLE.")
    L += ["", "## Run it", "", "```bash",
          f"uv run --with pyyaml packages/strategy/workflow_author.py --idea {i['id']} --client ongea-pesa", "```", ""]
    return "\n".join(L)


def render_index(props: list[dict[str, Any]], families: dict[str, str]) -> str:
    L = ["# Proposals for the 50 ideas", "",
         "Generated by `packages/strategy/proposals.py`. Each links its studio template and its diagram "
         "(`docs/diagrams/ideas/`). Planning estimates, not forecasts.", "",
         "Not ready counts declared gaps, steps that need setup (a `docs/BLOCKERS.md` item) and, as one, any models "
         "without a public source.", "",
         "| ID | Idea | Family | Price | Base revenue | Base margin | First cash | Runs today | Not ready | Gate |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for p in props:
        i, c = p["idea"], p["costed"]
        gate = " ".join(g for g, on in (("18+", i["family"] == "adult" or any(s["adult"] for s in p["steps"])),
                                        ("Consent", bool(p["wf"].get("consent_required")))) if on) or "—"
        not_ready = len(p["gaps"]) + len(p["setup"]) + (1 if p["blocked_models"] else 0)
        L.append(f"| {i['id']} | [{i['name']}]({i['id'].lower()}-{slug(i['name'])}.md) | {families[i['family']]} | "
                 f"{_m(i['price_usd'])} | {_m(c.base['mrr'])} | {c.base['margin']:.0%} | {i['first_cash_days']} d | "
                 f"{round(p['ready_share'] * 100)}% | {not_ready or '—'} | {gate} |")
    return "\n".join(L) + "\n"


def build_all() -> tuple[list[dict[str, Any]], dict[str, str]]:
    doc = bos.load()
    cat = {n["kind"]: n for n in json.loads(CATALOG.read_text(encoding="utf-8"))["nodes"]}
    models = model_status()
    return [build(c.idea, c, cat, models) for c in bos.costed_all(doc)], doc["families"]


def main() -> int:
    argparse.ArgumentParser(description="Write docs/proposals/ for the 50 ideas.").parse_args()
    props, families = build_all()
    OUT.mkdir(parents=True, exist_ok=True)
    for p in props:
        i = p["idea"]
        (OUT / f"{i['id'].lower()}-{slug(i['name'])}.md").write_text(render(p, families), encoding="utf-8")
    (OUT / "README.md").write_text(render_index(props, families), encoding="utf-8")
    print(f"wrote {len(props)} proposals to {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
